# Generated by Django 2.2 on 2020-01-09 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='logger.Category')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repitions', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('time', models.IntegerField(null=True)),
                ('distance', models.IntegerField(null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.Exercise')),
                ('workout_session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='logger.WorkoutSession')),
            ],
        ),
    ]
