# Generated by Django 3.0.2 on 2020-01-13 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20200109_0526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_exercise',
            old_name='repitions',
            new_name='repititions',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
    ]
