# Generated by Django 3.0.2 on 2020-01-15 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_auto_20200113_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_exercise',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='user_exercise',
            name='time',
        ),
    ]
